publicHoistPattern:
  - '*eslint*'
  - '*prettier*'

allowBuilds:
  '@openapitools/openapi-generator-cli': true
  nx: true

packages:
  - examples/*
  - packages/*
  - '!/packages/oauth2-cli'
  - packages/oauth2-cli/*