/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applicant_file": {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path?: never;
            cookie?: never;
        };
        /** List Admissions: Applicant Files */
        get: operations["list_admissions_applicant_files"];
        put?: never;
        /** Create Admissions: Applicant Files */
        post: operations["create_admissions_applicant_files"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applicant_file/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        /** Read Admissions: Applicant Files */
        get: operations["read_admissions_applicant_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ap_invoices/{invoice_id}/files": {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path: {
                /** @description Record ID */
                invoice_id: number;
            };
            cookie?: never;
        };
        /** List Finance: AP Invoice Files */
        get: operations["list_finance_ap_invoice_files"];
        put?: never;
        /** Create Finance: AP Invoice Files */
        post: operations["create_finance_ap_invoice_files"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ap_invoices/{invoice_id}/files/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path: {
                /** @description Record ID */
                invoice_id: number;
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        /** Read Finance: AP Invoice Files */
        get: operations["read_finance_ap_invoice_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/person_photo": {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Person Photo */
        post: operations["create_person_photo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/person_photo/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        /** Read Person Photo */
        get: operations["read_person_photo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        post: {
            data: {
                /** @description File ID */
                id: number;
            };
            /**
             * @description - Make request using PUT method
             *     - Provide file in binary format
             *     - Only first upload is accepted
             *     - Expires after 5 minutes
             *     - Allowed file types: `image/jpg`, `image/jpeg`, `image/png`, `image/gif`
             *     - Max file size: 2 MB
             */
            upload_url: string;
        };
        /** @description HTTP response codes describe the error type. See here for a list of HTTP response codes and their meanings: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status */
        error: {
            /** @description The description of the error */
            error: string;
            /** @description A unique ID for this specific error. Please provide this error id when you ask for help with an error. */
            error_id: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Page number */
        page_number: number;
        /** @description Number of records per page (for collection endpoints) */
        page_size: number;
        /** @description Include Value Lists in response */
        value_lists: "include";
        /** @description API Revision */
        api_revision: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_admissions_applicant_files: {
        parameters: {
            query?: {
                /** @description Person ID */
                person_id?: number;
                /**
                 * @description Year Applying For
                 *
                 *     Person Year Applying For
                 */
                year_applying_for?: number;
                /** @description School Year */
                school_year?: number;
            };
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
                /** @description Page number */
                "X-Page-Number"?: components["parameters"]["page_number"];
                /** @description Number of records per page (for collection endpoints) */
                "X-Page-Size"?: components["parameters"]["page_size"];
                /** @description Include Value Lists in response */
                "X-API-Value-Lists"?: components["parameters"]["value_lists"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description File ID */
                            readonly id: number;
                            /** @description Person ID */
                            person_id: number;
                            /** @description API Upload Status */
                            status: number;
                            /** @description API Upload Error */
                            error: string;
                            /** @description Description (Text) */
                            description: string;
                            /** @description Classification */
                            classification: string;
                            /**
                             * @description Year Applying For
                             *
                             *     Person Year Applying For
                             */
                            year_applying_for: number;
                            /** @description School Year */
                            school_year: number;
                            /** @description Notes */
                            notes: string;
                            /** @description Applicant File Download */
                            readonly download_url: string;
                        }[];
                        /** @description Present only with header `X-API-Value-Lists = include` */
                        readonly value_lists?: {
                            /** @description An array of field names from `data` that this value list goes with */
                            fields: ("status" | "year_applying_for" | "school_year")[];
                            /** @description An array of value list items whose `id` field matches the value in the response data */
                            items: {
                                id: string;
                                description: string;
                                category?: number;
                                sort_key: number;
                                obsolete?: boolean;
                            }[];
                            /** @description An array of "category" objects, which allow you to partition the value list items according to their category field */
                            categories: {
                                id: number;
                                description: string;
                                sort_key: number;
                            }[];
                        }[];
                    };
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    create_admissions_applicant_files: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    data: {
                        /** @description File ID */
                        readonly id?: number;
                        /** @description Person ID */
                        person_id?: number;
                        /** @description Description (Text) */
                        description?: string;
                        /** @description Classification */
                        classification?: string;
                        /**
                         * @description Year Applying For
                         *
                         *     Person Year Applying For
                         */
                        year_applying_for?: number;
                        /** @description School Year */
                        school_year?: number;
                        /** @description Notes */
                        notes?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["post"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    read_admissions_applicant_files: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
                /** @description Include Value Lists in response */
                "X-API-Value-Lists"?: components["parameters"]["value_lists"];
            };
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description File ID */
                            readonly id: number;
                            /** @description Person ID */
                            person_id: number;
                            /** @description API Upload Status */
                            status: number;
                            /** @description API Upload Error */
                            error: string;
                            /** @description Description (Text) */
                            description: string;
                            /** @description Classification */
                            classification: string;
                            /**
                             * @description Year Applying For
                             *
                             *     Person Year Applying For
                             */
                            year_applying_for: number;
                            /** @description School Year */
                            school_year: number;
                            /** @description Notes */
                            notes: string;
                            /** @description Applicant File Download */
                            readonly download_url: string;
                        };
                        /** @description Present only with header `X-API-Value-Lists = include` */
                        readonly value_lists?: {
                            /** @description An array of field names from `data` that this value list goes with */
                            fields: ("status" | "year_applying_for" | "school_year")[];
                            /** @description An array of value list items whose `id` field matches the value in the response data */
                            items: {
                                id: string;
                                description: string;
                                category?: number;
                                sort_key: number;
                                obsolete?: boolean;
                            }[];
                            /** @description An array of "category" objects, which allow you to partition the value list items according to their category field */
                            categories: {
                                id: number;
                                description: string;
                                sort_key: number;
                            }[];
                        }[];
                    };
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    list_finance_ap_invoice_files: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
                /** @description Page number */
                "X-Page-Number"?: components["parameters"]["page_number"];
                /** @description Number of records per page (for collection endpoints) */
                "X-Page-Size"?: components["parameters"]["page_size"];
                /** @description Include Value Lists in response */
                "X-API-Value-Lists"?: components["parameters"]["value_lists"];
            };
            path: {
                /** @description Record ID */
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Record ID */
                            invoice_id: number;
                            /** @description Invoice Number */
                            invoice_number: string;
                            /** @description Name */
                            name: string;
                            /** @description File ID */
                            readonly id: number;
                            /** @description Description (Text) */
                            description: string;
                            /** @description Notes */
                            notes: string;
                            /** @description File Download */
                            readonly download_url: string;
                        }[];
                        /** @description Present only with header `X-API-Value-Lists = include` */
                        readonly value_lists?: Record<string, never>[];
                    };
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    create_finance_ap_invoice_files: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path: {
                /** @description Record ID */
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    data: {
                        /** @description Record ID */
                        invoice_id?: number;
                        /** @description Invoice Number */
                        invoice_number: string;
                        /** @description Name */
                        name?: string;
                        /** @description File ID */
                        readonly id?: number;
                        /** @description Description (Text) */
                        description?: string;
                        /** @description Notes */
                        notes?: string;
                        /** @description File Download */
                        readonly download_url?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["post"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    read_finance_ap_invoice_files: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
                /** @description Include Value Lists in response */
                "X-API-Value-Lists"?: components["parameters"]["value_lists"];
            };
            path: {
                /** @description Record ID */
                invoice_id: number;
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Record ID */
                            invoice_id: number;
                            /** @description Invoice Number */
                            invoice_number: string;
                            /** @description Name */
                            name: string;
                            /** @description File ID */
                            readonly id: number;
                            /** @description Description (Text) */
                            description: string;
                            /** @description Notes */
                            notes: string;
                            /** @description File Download */
                            readonly download_url: string;
                        };
                        /** @description Present only with header `X-API-Value-Lists = include` */
                        readonly value_lists?: Record<string, never>[];
                    };
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    create_person_photo: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    data: {
                        /** @description File ID */
                        readonly id?: number;
                        /** @description Person ID */
                        person_id: number;
                        /** @description Notes */
                        notes?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["post"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
    read_person_photo: {
        parameters: {
            query?: never;
            header?: {
                /** @description API Revision */
                "X-API-Revision"?: components["parameters"]["api_revision"];
                /** @description Include Value Lists in response */
                "X-API-Value-Lists"?: components["parameters"]["value_lists"];
            };
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description API Revision */
                    "X-API-Revision": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description File ID */
                            readonly id: number;
                            /** @description Person ID */
                            person_id: number;
                            /** @description API Upload Status */
                            status: number;
                            /** @description API Upload Error */
                            error: string;
                            /**
                             * @description Person Photo URL/W Expiration
                             *
                             *     This URL is private and expires 24 hours after the API request is completed.
                             */
                            readonly download_url: string;
                            /** @description Notes */
                            notes: string;
                            /**
                             * Format: date-time
                             * @description Last Modified Date
                             */
                            readonly last_modified_date: string;
                        };
                        /** @description Present only with header `X-API-Value-Lists = include` */
                        readonly value_lists?: {
                            /** @description An array of field names from `data` that this value list goes with */
                            fields: "status"[];
                            /** @description An array of value list items whose `id` field matches the value in the response data */
                            items: {
                                id: string;
                                description: string;
                                category?: number;
                                sort_key: number;
                                obsolete?: boolean;
                            }[];
                            /** @description An array of "category" objects, which allow you to partition the value list items according to their category field */
                            categories: {
                                id: number;
                                description: string;
                                sort_key: number;
                            }[];
                        }[];
                    };
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
            /** @description > Note: Be sure to check the HTTP response code for these errors as well */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error"];
                };
            };
        };
    };
}
